import Link from "next/link";
import type { ReactNode, CSSProperties } from "react";
import brand from "@/content/brand-paths.json";

export const Arrow = ({ className = "arrow" }: { className?: string }) => (
  <svg className={className} width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden>
    <path d="M2 8h11M9 3.5 13.5 8 9 12.5" stroke="currentColor" strokeWidth="1.5" />
  </svg>
);

/* Brand paths are generated by scripts/make_logo.py (see public/brand/ for all lockups). */
const MarkPath = () => (
  <path d={brand.mark} transform="rotate(45 16 16)" fill="none" stroke="currentColor" strokeWidth={brand.markStroke} strokeLinecap="round" />
);

export function Mark({ size = 26 }: { size?: number }) {
  // A 3×3 plain weave turned 45° — threads passing over and under in turn.
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" aria-hidden>
      <MarkPath />
    </svg>
  );
}

const LOGO_GAP = 12;
const LOGO_W = 32 + LOGO_GAP + brand.wordWidth;

export function Logo({ className = "", height = 24 }: { className?: string; height?: number }) {
  // The SVG keeps the original logo's 26px box (artwork drawn at `height` inside it) and the
  // invisible text keeps its 19px line, so baseline and surrounding layout are unchanged.
  const pad = ((26 / height) * 32 - 32) / 2;
  return (
    <span className={`inline-flex items-center ${className}`}>
      <svg height={26} width={(height * LOGO_W) / 32} viewBox={`0 ${-pad} ${LOGO_W} ${32 + 2 * pad}`} aria-hidden>
        <MarkPath />
        <path d={brand.word} transform={`translate(${32 + LOGO_GAP} ${16 + brand.wordCap / 2})`} fill="currentColor" />
      </svg>
      <span aria-hidden className="invisible w-0 overflow-hidden text-[19px] font-semibold">W</span>
      <span className="sr-only">WeaveSources</span>
    </span>
  );
}

export function Button({
  href,
  children,
  variant = "primary",
  className = "",
  arrow = true,
}: {
  href: string;
  children: ReactNode;
  variant?: "primary" | "accent" | "ghost" | "light";
  className?: string;
  arrow?: boolean;
}) {
  return (
    <Link href={href} className={`btn btn-${variant} ${className}`}>
      {children}
      {arrow && <Arrow />}
    </Link>
  );
}

export function Tbc({ children }: { children: ReactNode }) {
  return (
    <span className="tbc" title="Placeholder — replace with verified information in src/content/site.ts">
      <span aria-hidden>◌</span> {children}
    </span>
  );
}

export function SectionHead({
  index,
  eyebrow,
  title,
  lede,
  className = "",
  align = "split",
}: {
  index?: string;
  eyebrow: string;
  title: ReactNode;
  lede?: ReactNode;
  className?: string;
  align?: "split" | "stack";
}) {
  return (
    <div className={`${align === "split" ? "grid gap-6 md:grid-cols-12 md:gap-10" : "max-w-3xl"} ${className}`}>
      <div className={align === "split" ? "md:col-span-7" : ""} data-reveal>
        <p className="eyebrow mb-5">
          {index && <span className="text-clay mr-3">{index}</span>}
          {eyebrow}
        </p>
        <h2 className="h2">{title}</h2>
      </div>
      {lede && (
        <div className={align === "split" ? "md:col-span-5 md:pt-12" : "mt-6"} data-reveal style={{ "--d": "120ms" } as CSSProperties}>
          <div className="lede">{lede}</div>
        </div>
      )}
    </div>
  );
}

export function PageHero({ eyebrow, title, lede, children }: { eyebrow: string; title: ReactNode; lede?: ReactNode; children?: ReactNode }) {
  return (
    <section className="wrap pt-36 pb-16 md:pt-44 md:pb-24">
      <p className="eyebrow mb-6" data-reveal>{eyebrow}</p>
      <h1 className="display max-w-5xl" data-reveal style={{ "--d": "80ms" } as CSSProperties}>{title}</h1>
      {lede && <div className="lede mt-8 max-w-2xl" data-reveal style={{ "--d": "160ms" } as CSSProperties}>{lede}</div>}
      {children && <div className="mt-10" data-reveal style={{ "--d": "220ms" } as CSSProperties}>{children}</div>}
    </section>
  );
}

const tones: Record<string, string> = {
  white: "#f8f6f1",
  stone: "#d9d1c3",
  sand: "#e6dccb",
  clay: "#c98466",
  charcoal: "#3b3935",
  sage: "#a9b09f",
};

/** Folded-towel illustration. Replace with real photography via `photo`. */
export function Towel({
  tone = "white",
  className = "",
  border = true,
  folded = true,
  style,
}: {
  tone?: string;
  className?: string;
  border?: boolean;
  folded?: boolean;
  style?: CSSProperties;
}) {
  const c = tones[tone] ?? tone;
  const dark = tone === "charcoal";
  return (
    <div
      className={`${className.includes("absolute") ? "" : "relative"} overflow-hidden ${folded ? "rounded-[14px]" : "rounded-[10px]"} ${className}`}
      style={{ ...style, boxShadow: "0 1px 0 rgb(255 255 255 / .5) inset, 0 20px 40px -24px rgb(40 30 20 / .35), 0 2px 6px -2px rgb(40 30 20 / .12)" }}
      aria-hidden
    >
      <div className="terry absolute inset-0" style={{ "--tone": c } as CSSProperties} />
      {border && (
        <div
          className="dobby absolute inset-x-0"
          style={{ bottom: folded ? "18%" : "8%", height: folded ? "13%" : "7%", backgroundColor: dark ? "rgb(255 255 255 / .06)" : "rgb(0 0 0 / .03)" }}
        />
      )}
      {folded && (
        <>
          <div className="absolute inset-x-0 top-0 h-[38%]" style={{ background: "linear-gradient(rgb(255 255 255 / .18), transparent)" }} />
          <div className="absolute inset-x-0 top-[46%] h-px" style={{ background: dark ? "rgb(0 0 0 / .35)" : "rgb(0 0 0 / .08)" }} />
          <div className="absolute inset-x-0 bottom-0 h-[30%]" style={{ background: "linear-gradient(transparent, rgb(0 0 0 / .06))" }} />
        </>
      )}
    </div>
  );
}

export function TowelStack({ tones: t = ["white", "stone", "sand"], className = "" }: { tones?: string[]; className?: string }) {
  return (
    <div className={`relative ${className}`} aria-hidden>
      {t.map((tone, i) => (
        <Towel
          key={i}
          tone={tone}
          className="absolute left-1/2 -translate-x-1/2"
          style={{ width: `${86 - i * 4}%`, height: "26%", bottom: `${i * 23}%`, zIndex: i + 1 }}
        />
      ))}
    </div>
  );
}

export function Placeholder({ label, className = "" }: { label: string; className?: string }) {
  return (
    <div className={`relative flex items-center justify-center rounded-2xl border border-dashed border-sand bg-linen/60 ${className}`}>
      <span className="tbc">{label}</span>
    </div>
  );
}
